name: Complex
on: [push]
jobs:
  ubuntujob:
    runs-on: ubuntu-latest
    steps:
      -run: date
  windowsjob:
    runs-on: windows-latest
    steps:
      -run: date
  macjob:
    runs-on: macos-latest
    steps:
      -run: date
  dependencyjob:
    needs: [ubuntujob, windowsjob, macjob]
    runs-on: macos-latest
    steps:
      -run: date
