name: Complex
on: [push]
jobs:
  ubuntujob:
    runs-on: ubuntu-latest
    steps:
    - name: ok
    - run: date
  windowsjob:
    runs-on: windows-latest
    steps:
    - run: date
  macjob:
    runs-on: macos-latest
    steps:
    - run: date

